version: '3.9'
services:
    nextjs:
        env_file:
            - .env.local
        build: .
        restart: always
    nginx:
        build: ./nginx
        restart: always
        ports:
            - 80:80
