
import { Card } from '@components/Card';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { globalStyles } from '../styles';
import Link from 'next/link';
import { firestore } from '@common/firebase';

interface Card {
  id: string;
  title: string;
  description: string;
}
interface Props {
  cards: Array<Card>
}

const Home: NextPage<Props> = ({ cards }) => {
  return (
    <div css={globalStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={globalStyles.main}>
        <h1 css={globalStyles.title}>
          ISR Demo
        </h1>

        <p css={globalStyles.description}>
          <Link prefetch={false} href={'/create'}><a>Add Card</a></Link>
        </p>

        <div css={globalStyles.grid}>
          {
            cards.map((card) => (
              <Link key={card.id} href={`/${encodeURIComponent(card.id)}`}>
                <a>
                  <Card
                    id={card.id}
                    title={card.title}
                    description={card.description}
                  />
                </a>
              </Link>
            ))
          }
        </div>
      </main>

      <footer css={globalStyles.footer}>
        <a
          css={globalStyles.footerLink}
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span css={globalStyles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const snapshot = await firestore.collection('cards').get();
  const data = snapshot.docs.map((doc) => ({ id: doc.id, ...(doc.data() as any) }))

  return {
    props: {
      cards: data
    }, // will be passed to the page component as props
  }
}

export default Home;
