
import { Card } from '@components/Card';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { globalStyles } from '../styles';
import Link from 'next/link';

const Home: NextPage = () => {
  return (
    <div css={globalStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={globalStyles.main}>
        <h1 css={globalStyles.title}>
          ISR Demo
        </h1>

        <p css={globalStyles.description}>
          <Link prefetch={false} href={'/create'}><a>Add Card</a></Link>
        </p>

        <div css={globalStyles.grid}>
          <Card
            id='1234'
            title='Documentation'
            description='Find in-depth information about Next.js features and API.'
            link='sdada'
          />
        </div>
      </main>

      <footer css={globalStyles.footer}>
        <a
          css={globalStyles.footerLink}
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{' '}
          <span css={globalStyles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
